### ISSUE TITLE
 Did you mean: 'inf'?

### ISSUE THREAD

**Issue by rusvo** [winycg/HCGNet#3]
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to data/cifar-10-python.tar.gz
100.0%
Extracting data/cifar-10-python.tar.gz to data
Files already downloaded and verified
==> Building model..
Traceback (most recent call last):
  File "/root/HCGNet/main_cifar.py", line 105, in <module>
    % (cal_param_size(net)/1e6, cal_multi_adds(net,)/1e9))
  File "/root/HCGNet/utils.py", line 228, in cal_multi_adds
    model.forward(data)
  File "/root/HCGNet/models/HCGNet_CIFAR.py", line 218, in forward
    features = self.features(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/HCGNet/models/HCGNet_CIFAR.py", line 148, in forward
    self.dropblock.step()
  File "/root/HCGNet/regularization/dropblock/scheduler.py", line 20, in step
    ix = np.log2(self.global_epoch / 10 + 1).astype(np.int)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by rusvo** [comment]
How i can fix it?

**Comment by winycg** [comment]
Please replace “ int” with "int64". Thanks.

**Comment by rusvo** [comment]
> Please replace “ int” with "int64". Thanks.

in main_cifar.py?

**Comment by rusvo** [comment]
im change int to int64 on scheduler.py

DESKTOP:~/HCGNet$ python3 main_cifar.py --dataset cifar10 --arch HCGNet_A1
Files already downloaded and verified
Files already downloaded and verified
==> Building model..
Params: 1.07M, Multi-adds: 0.16G
Traceback (most recent call last):
  File "/home/rusvo/HCGNet/main_cifar.py", line 263, in <module>
    train(epoch)
  File "/home/rusvo/HCGNet/main_cifar.py", line 178, in train
    lr = adjust_lr(optimizer, epoch)
  File "/home/rusvo/HCGNet/main_cifar.py", line 154, in adjust_lr
    i = int64(math.log2(epoch / args.sgdr_t + 1))
NameError: name 'int64' is not defined
